# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: '$(Date:yyyy-MM-dd)$(Rev:.rr)__$(SourceBranchName)'

# trigger only on tool changes
trigger:
  batch: true
  paths:
    include:
    - src/*

resources:
- repo: self

variables:
  VersionNumber: '1.0.0'
  dockerServiceConnection: 'Docker Hub (OITC)'

stages:
- stage: Build
  displayName: 'Build #CHN256234 - Interval Merger'
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      # Login to Docker registry
      - task: Docker@2
        displayName: 'Login to Docker Hub'
        inputs:
          command: login
          containerRegistry: $(dockerServiceConnection)

      # build docker image and push it to registry
      - task: Docker@2
        displayName: 'Building and pushing the repository'
        inputs:
          containerRegistry: $(dockerServiceConnection)
          repository: 'oitc/CHN256234'
          command: 'buildAndPush'
          #command: 'build'
          Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
          buildContext: '.'
          tags: |
            $(VersionNumber)
            latest

